class_name TrainerCatalogData
extends Resource

## Precomputed trainer catalog (families + variants + category + credit).
## Generated by tools/sync_trainer_sprites.gd via TrainerCatalogBuilder — do
## not hand-edit. Shipped as a normal Resource so the game loads it with a
## single load() instead of re-scanning/reclassifying ~1500 sprites at
## runtime on every player's machine (or browser tab).

const CATEGORY_ORDER: Array[String] = ["protagonists", "teams", "generic", "characters"]
const CATEGORY_LABELS := {
	"protagonists": "Protagonists",
	"teams": "Teams",
	"generic": "Trainers",
	"characters": "Characters",
}

@export var families: Array[TrainerCatalogFamilyData] = []
@export var generated_unix_time: int = 0

func _init() -> void:
	pass
